name: PEP8, Types and Docs Check

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: |
          python -m pip install ".[dev]" --upgrade
      - name: Lint with flake8
        run: |
          flake8 fsrl --config=setup.cfg --count --show-source --statistics
      - name: Code formatter
        run: |
          yapf -r -d --style=setup.cfg fsrl
          isort --settings-path setup.cfg --check --diff fsrl
      - name: Documentation test
        run: |
          make check-docstyle
          make spelling
